version: "3.9"

services:
    kafka-manager:
        container_name: ${HTTP_SERVER_NAME}
        build: .
        ports:
            - ${HTTP_SERVER_PORT}:8081
        depends_on:
            - kafka-manager-db
            - kafka
            - zookeeper
        environment:
            ENV: ${ENV_TYPE}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_DRIVER_NAME: ${DB_DRIVER_NAME}
            DB_USER_NAME: ${DB_USER_NAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_SSL_MODE: ${DB_SSL_MODE}
            DB_MAX_CONNS: ${DB_MAX_CONNS}
            KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
            KAFKA_TOPIC: ${KAFKA_TOPIC}
            KAFKA_BROKER: ${KAFKA_BROKER}
            ZOOKEEPER_HOST: ${ZOOKEEPER_HOST}
            ZOOKEEPER_PORT: ${ZOOKEEPER_PORT}
            HTTP_SERVER_TIMEOUT: ${HTTP_SERVER_TIMEOUT}
            HTTP_SERVER_IDLE_TIMEOUT: ${HTTP_SERVER_IDLE_TIMEOUT}
            HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}
            HTTP_SERVER_NAME: ${HTTP_SERVER_NAME}

    kafka-manager-db:
        restart: always
        container_name: ${DB_NAME}
        image: postgres:latest
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USER_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}

    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        ports:
            - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}

    kafka:
        image: wurstmeister/kafka:latest
        container_name: kafka
        ports:
            - ${KAFKA_PORT}:${KAFKA_PORT}
        expose:
            - ${KAFKA_EXPOSE_PORT}
        environment:
            KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
            KAFKA_LISTENER_NAMES: ${KAFKA_LISTENER_NAMES}
            KAFKA_LISTENERS: ${KAFKA_LISTENERS}
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
            KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
            KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
            KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}