basePath: /api/v1
info:
  contact:
    email: Z_shevelev@mail.ru
    name: API Support
  description: This API manages Kafka messages by allowing you to create orders and
    check their status.
  title: Kafka Manager API
  version: "1.0"
paths: {}
swagger: "2.0"
